HeadNode: 
  CustomActions: 
    OnNodeConfigured: 
      Script: "s3://hpc-scripts1234/install-pwb-config.sh"
  Iam: 
    S3Access: 
      - BucketName: hpc-scripts1234
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  InstanceType: t2.xlarge
  Networking: 
    SubnetId: subnet-03259a81db5aec449
  LocalStorage:
    RootVolume:
      Size: 100 
  InternalSharedStorageType: Efs
  Ssh:
    KeyName: michael.mayer@posit.co-keypair-for-pulumi-1700646177 
Image: 
  Os: ubuntu2004
  CustomAmi: ami-09901d00eff671747
Region: eu-west-1
Scheduling: 
  Scheduler: slurm
  SlurmSettings:
     EnableMemoryBasedScheduling: true
  SlurmQueues: 
    - Name: all 
      ComputeResources:
        - Name: rstudio 
          InstanceType: t2.xlarge 
          MaxCount: 10 
          MinCount: 1
          Efa:
            Enabled: FALSE
      CustomActions:
        OnNodeConfigured:
          Script: "s3://hpc-scripts1234/config-compute.sh"
      Iam:
        S3Access:
          - BucketName: hpc-scripts1234
      Networking:
        PlacementGroup:
          Enabled: FALSE
        SubnetIds:
          - subnet-03259a81db5aec449

    - Name: gpu 
      ComputeResources:
        - Name: large
          InstanceType: p3.2xlarge
          MaxCount: 1
          MinCount: 0
          Efa:
            Enabled: FALSE
      CustomActions:
        OnNodeConfigured:
          Script: "s3://hpc-scripts1234/config-compute.sh"
      Iam:
        S3Access:
          - BucketName: hpc-scripts1234
      Networking:
        PlacementGroup:
          Enabled: FALSE
        SubnetIds: 
          - subnet-03259a81db5aec449


LoginNodes:
  Pools:
    - Name: login
      Count: 2 
      InstanceType: t2.xlarge
      Networking:
        AdditionalSecurityGroups: 
          - sg-09ca531e5331195f1
        SubnetIds: 
          - subnet-03259a81db5aec449
      Ssh:
        KeyName: michael.mayer@posit.co-keypair-for-pulumi-1700646177 

DevSettings:
  Timeouts:
    HeadNodeBootstrapTimeout: 5400  # timeout in seconds
    ComputeNodeBootstrapTimeout: 5400  # timeout in seconds

SharedStorage:
  - MountDir: /home
    Name: home
    StorageType: FsxLustre
    FsxLustreSettings:
      StorageCapacity: 1200
      DeploymentType: SCRATCH_2

DirectoryService:
  DomainName: pwb.posit.co
  DomainAddr: ldap://pwb.posit.co
  PasswordSecretArn: arn:aws:secretsmanager:eu-west-1:637485797898:secret:SimpleADPassword-2898387-BQn4mT 
  DomainReadOnlyUser: cn=Administrator,cn=Users,dc=pwb,dc=posit,dc=co
  GenerateSshKeysForUsers: true
  AdditionalSssdConfigs: 
    override_homedir : /home/%u
    ldap_id_use_start_tls : false
    ldap_tls_reqcert : never
    ldap_auth_disable_tls_never_use_in_production : true

Tags:
  - Key: rs:environment
    Value: development
  - Key: rs:owner
    Value: michael.mayer@posit.co 
  - Key: rs:project
    Value: solutions 
