HeadNode: 
  CustomActions: 
    OnNodeConfigured: 
      Script: "s3://hpc-scripts1234/install-pwb-config.sh"
  Iam: 
    S3Access: 
      - BucketName: hpc-scripts1234
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  InstanceType: t2.xlarge
  Networking: 
    SubnetId: subnet-03259a81db5aec449
  LocalStorage:
    RootVolume:
      Size: 100 
  Ssh:
    KeyName: michael
Image: 
  Os: ubuntu2004
  CustomAmi: ami-06703fc92368ea185
Region: eu-west-1
Scheduling: 
  Scheduler: slurm
  SlurmSettings:
     EnableMemoryBasedScheduling: true
  SlurmQueues: 
    - Name: all 
      ComputeResources:
        - Name: rstudio 
          InstanceType: t2.xlarge
          MaxCount: 10 
          MinCount: 1
          Efa:
            Enabled: FALSE
      CustomActions:
        OnNodeConfigured:
          Script: "s3://hpc-scripts1234/config-compute.sh"
      Iam:
        S3Access:
          - BucketName: hpc-scripts1234
      Networking:
        PlacementGroup:
          Enabled: FALSE
        SubnetIds:
          - subnet-03259a81db5aec449

    - Name: gpu 
      ComputeResources:
        - Name: large
          InstanceType: p3.16xlarge
          MaxCount: 1
          MinCount: 0
          Efa:
            Enabled: FALSE
      CustomActions:
        OnNodeConfigured:
          Script: "s3://hpc-scripts1234/config-compute.sh"
      Iam:
        S3Access:
          - BucketName: hpc-scripts1234
      Networking:
        PlacementGroup:
          Enabled: FALSE
        SubnetIds: 
          - subnet-03259a81db5aec449


LoginNodes:
  Pools:
    - Name: login
      Count: 2 
      InstanceType: t2.xlarge
      Networking:
        AdditionalSecurityGroups: 
          - sg-0838ae772a776ab8e
        SubnetIds: 
          - subnet-03259a81db5aec449
      Ssh:
        KeyName: michael

DevSettings:
  Timeouts:
    HeadNodeBootstrapTimeout: 5400  # timeout in seconds
    ComputeNodeBootstrapTimeout: 5400  # timeout in seconds

SharedStorage:
  - MountDir: /data
    Name: data
    StorageType: FsxLustre
    FsxLustreSettings:
      StorageCapacity: 1200
      DeploymentType: SCRATCH_2

Tags:
  - Key: rs:environment
    Value: development
  - Key: rs:owner
    Value: michael.mayer@rstudio.com
  - Key: rs:project
    Value: solutions 
